language: node_js

node_js:
  - '0.12'

env:
  global:
    - secure: "TmS/FRRiUhCu+E2fjuOSWMMxEmyRP8Ljez1IMbnxDueqIyR23Pb6GjuiJGz/nVtgRNJxwra5Ujm4nZ+5fyAPK4mfUNXUPDPFBWBD1chR46wBAJbPI1HajBAFXIAbF8YEOvXk9NBld4llWdkdonqX0DXvB9S4EBUzaZwGnlx7e+I="
    - secure: "ZvXrYcgnnv2RA+fbf9l+ab579XEvoghkUvwp80L23BxbbNc9i9WojiWwbNjGwnE0t0Yv8kkhQcE3aha0W0Di6YUXPUdh5geUQmT0d1dFPcd/J1lCRO5MrTbpEkI00LuUdkgQHSctz3dZcwwVpkNsC6+wY8YY/Q1vlRIK4bj+JfY="

branches:
  only:
  - master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod +x ./travis_build.sh
  - npm install --quiet -g gulp karma bower
  - bower install

script:
  - ./travis_build.sh

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && gulp publish
