language: node_js

node_js:
  - '0.12'

env:
  global:
    - secure: "TmS/FRRiUhCu+E2fjuOSWMMxEmyRP8Ljez1IMbnxDueqIyR23Pb6GjuiJGz/nVtgRNJxwra5Ujm4nZ+5fyAPK4mfUNXUPDPFBWBD1chR46wBAJbPI1HajBAFXIAbF8YEOvXk9NBld4llWdkdonqX0DXvB9S4EBUzaZwGnlx7e+I="
    - secure: "QDSG6xP/C5NpZZTYC3kBDSofYujUOMd1sJTjZNkCtGJ1QX+D8yYGZBpWwz36bX8qZcvAUA9fOfvirzCLCBPYPf9EA+B1f0tz9MBrBmGr59rups3OZdflQMIEFarFi+miaMvG1HF2A+SbnzLv+lKrPhe6Fw0INjJB4H+gUspUM6w="

branches:
  only:
  - master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod +x ./travis_build.sh
  - npm install --quiet -g gulp karma bower
  - bower install

script:
  - ./travis_build.sh

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && gulp publish
