language: node_js

node_js:
  - '0.12'

env:
  global:
    - secure: "nn7s0n4CEqpHaU8mWtBUKyFWUzm+nYcG8aHrzmRK4A8PXC8+azo63vvti7QlRkDxlnS+vkd1SEBBd9YLxCmr8SHiu1b/QTseEWfZa09D1PNQmSX6C/sabAxHL6MXZ/j4ZLtQ53naD4yoNBXRwZ2kphkc09FJed8Ok+m+Hj8/7Ls="
    - secure: "bzjmmm8WVt6TKNWUTVTy7c32x4fFJ53i7ypi5ucmC3NvXc17/JkacUfMQ76P6drLKgEO6olIyM4U+ZTS4ODiEorDMSvLvIUxaUM4qBS+hHM8S1lN0BZn5neNDumdl7MYYBH1hCNgwxlWdBnSzUkgY8pATSSciZC2anIXp+7Q/1k="

branches:
  only:
  - master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod +x ./travis_build.sh
  - npm install --quiet -g gulp karma bower
  - bower install

script:
  - ./travis_build.sh

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && gulp publish
