language: node_js

node_js:
  - '0.12'

env:
  global:
    - secure: "fa5fArbwOxcpbv1uLZnIdjfkBEw/k97qrwya+EoFPSwpnoyS4tv/J27fgDdQxp2S83ge7OafHccJkgPDZYrCgOqqbSiVFOaSHnX8eyWkC+k3MqAY5s2rfjdFE/NS3sA3yRV+AEw8xDJ4xFZhJXmUmb1lpuK3+VYAn5ElEtKLGLU="
    - secure: "EKFllxWbaNO41LKRUaaPG+wn+37OLGJ9yAUx4F4agnnM8c8OALzGE34xbzKn5qoza/JvmobrVUhzKmp0/HiuwKjOX0NfJAKp2mIeMy5G64dhaEGFPeeviIzOCJ2DTR/IIEhACidQjquFy+WExtDCbt8Xzgq+38lcKytuE4GEIZM="

branches:
  only:
  - master

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - chmod +x ./travis_build.sh
  - npm install --quiet -g gulp karma bower
  - bower install

script:
  - ./travis_build.sh

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && gulp publish
